# Oliver Orejola
# Created: 9/27/21
# 
#------------------------- [ Libraries ]----------------------------
library(somebm)
library(wavelets)
library(diptest)
library(MASS)
library("tidyverse")
#------------------------- [ Functions ]----------------------------
coordinate_matrix <- function(n){
  mat <- c()
  for(i in 1:n){
    x <- rnorm(n)
    col <- x/sqrt(sum(x^2)) 
    mat <- append(mat,col)
  }
  return(matrix(mat, n, n,byrow = FALSE))
}

low_dim_wavelet_sampe_covariances<- function(level,scales,Hursts, mixed = FALSE){
  N = 2^level #Path size
  #n_j = N/(2^scale)
  p = length(Hursts)
  P <- coordinate_matrix(p)
  wavelet_list <- list()
  #Create blank list of NA from which we will construct List of Vectors
  for(j in scales){
    wavelet_list <- append(wavelet_list, c(NA))
  }
  for(H in Hursts){
    fractional_brownian <-  N^H*fbm(hurst = H, n = N)
    print(H)
    wavelet_transform <- dwt(fractional_brownian, filter = "d4", n.levels = level, boundary = "reflection")
    i = 1
    for(j in scales){  
      wavelet_list[[i]] <- append(wavelet_list[[i]] ,unlist(wavelet_transform@W[j]))
      i <- i+1
    }
  }
  # Remove NA generated by initiation of list of blank vectors
  for(i in 1:length(wavelet_list)){
    wavelet_list[[i]] <-wavelet_list[[i]][!is.na(wavelet_list[[i]])]
  }
  
  i=1
  for(j in scales){
    effective_sample_size = N/(2^j) #
    wavelet_mat <- matrix(wavelet_list[[i]], effective_sample_size, p,byrow = FALSE)  # convert vectors into matrices 
    if(mixed == TRUE){ 
      mixed_wavlet_mat <- wavelet_mat %*% t(P)
      mixed_wavlet_product <- crossprod(mixed_wavlet_mat)
      eigenvalues <- eigen(1/effective_sample_size *mixed_wavlet_product)$values #add list of eigenvalues
    }
    else{
      wavelet_product <-  crossprod(wavelet_mat)
      eigenvalues <- eigen(1/effective_sample_size *wavelet_product)$values
    }
    wavelet_list[[i]]  <- eigenvalues
    i=i+1
  }
  return(wavelet_list)
}

test<- low_dim_wavelet_sampe_covariances(8,6,c(0.2,0.8))
#------[ Simulations and Data generation ]----------
set.seed(1000)
#-----------------Regression -------------------------

delta_estimator <- function(hurst,min_level,max_level,runs){
  data <- c()
  data_sd <- c()
  data_RMSE <- c()
  j1 <- 3 #Fixed at 3 to match paper
  for(level in min_level:max_level){
    mc_delta<- c()
    data_SE <- c()
    j2 <- level - 2 # set j2 to  log_2(path_size) - number of vanishing moments
    l = j2-j1+1
    X <- matrix(c(c(j1:j2),rep(1,l)),2,l,byrow=TRUE)
    weights <- ginv(X)%*%c(1,0)
    for(r in 1:runs){
      wavelet_eigen <- low_dim_wavelet_sampe_covariances(level,c(j1:j2),hurst)
      delta <- 0
      for(i in 1:l){
        delta<- delta + weights[i]*log(wavelet_eigen[[i]],base=2)
      }
      data_SE <- append(data_SE, (delta - (2*hurst + 1))**2)
      mc_delta <-append(mc_delta,delta)
    }
    rescaled_delta <- (mc_delta - rep(1,length(mc_delta)))*0.5
    data <- append(data, mean(rescaled_delta))
    data_sd <- append(data_sd, sd(rescaled_delta ))
    data_RMSE <- append(data_RMSE,sqrt(mean(data_SE)))
  }
  return(list(data,data_sd,data_RMSE))
}


delta_estimator_multivariate <- function(hurst,min_level,max_level,runs){
  data <- list() #Initalize blank lists
  data_sd <- list()
  data_RMSE <- list()
  j1 <- 3 #Fixed at 3 to match paper
  level_index=1
  for(level in min_level:max_level){
    mc_delta<- list()
    data_SE <- list()
    j2 <- level - 2 # set j2 to  log_2(path_size) - number of vanishing moments
    l = j2-j1+1
    X <- matrix(c(c(j1:j2),rep(1,l)),2,l,byrow=TRUE)
    weights <- ginv(X)%*%c(1,0)
    for(r in 1:runs){
      wavelet_eigen <- low_dim_wavelet_sampe_covariances(level,c(j1:j2),hurst)
      delta <- rep(0,length(hurst))
      for(i in 1:l){
        sorted_eigen_values <-sort(wavelet_eigen[[i]])
        delta<- delta + weights[i]*log(wavelet_eigen[[i]],base=2)
      }
      mc_delta[[r]] <- delta 
      data_SE[[r]] <- (delta - (2*hurst + 1))**2
      
    }
   mc_delta <- as.data.frame(mc_delta)
   data_SE <- as.data.frame(data_SE)
   data[[level_index]]<- apply(mc_delta,1,mean)
   data_sd[[level_index]]<- apply(mc_delta,1,sd)*0.5
   data_RMSE[[level_index]]<- sqrt(apply(data_SE,1,mean))
   level_index<- level_index+1
    #rescaled_delta <- (mc_delta - rep(1,length(mc_delta)))*0.5
    #data <- append(data, mean(rescaled_delta))
   # data_sd <- append(data_sd, sd(rescaled_delta ))
    #<- append(data_RMSE,sqrt(mean(data_SE)))
  }
  return(list(data,data_sd,data_RMSE))
}
test<- delta_estimator_multivariate(c(0.4,0.4),10,15,100)

Hurst_1 = 0.25
Hurst_2 = 0.4
Hurst_3 = 0.75
min_level = 10 #range of octaves to simulate over
max_level = 20 
runs = 1000


data_1 <- delta_estimator(Hurst_1,min_level,max_level,runs)
data_2 <- delta_estimator(Hurst_2,min_level,max_level,runs)
data_3 <- delta_estimator(Hurst_3,min_level,max_level,runs)

par(mfrow=c(3,3))

bias <- data_1[[1]] - Hurst_1
plot(c(min_level:max_level),bias, type = "l"
     , xlab = "path size"
     , ylab = "bias"
     , main = paste("Delta Estimator bias vs Path size, Hurst = ", Hurst_1))

plot(c(min_level:max_level),log(data_1[[2]],base=2), type = "o"
     , xlab = "path size"
     , ylab = "log_2(std)"
     , main = paste("runs  = ", runs))

plot(c(min_level:max_level),data_1[[3]], type = "o"
     , xlab = "path size"
     , ylab = "RMSE"
     , main = paste("runs  = ", runs))

bias <- data_2[[1]] - Hurst_2
plot(c(min_level:max_level),bias, type = "l"
     , xlab = "path size"
     , ylab = "bias"
     , main = paste("Delta Estimator bias vs Path size, Hurst = ", Hurst_2))

plot(c(min_level:max_level),log(data_2[[2]],base=2), type = "o"
     , xlab = "path size"
     , ylab = "log_2(std)"
     , main = paste("runs  = ", runs))

plot(c(min_level:max_level),data_2[[3]], type = "o"
     , xlab = "path size"
     , ylab = "RMSE"
     , main = paste("runs  = ", runs))


bias <- data_3[[1]] - rep(Hurst_3,length( data_3[[1]]))
plot(c(min_level:max_level),bias, type = "l"
     , xlab = "path size"
     , ylab = "bias"
     , main = paste("Delta Estimator bias vs Path size, Hurst = ", Hurst_3))

plot(c(min_level:max_level),log(data_3[[2]],base=2), type = "o"
     , xlab = "path size"
     , ylab = "log_2(std)"
     , main = paste("runs  = ", runs))

plot(c(min_level:max_level),data_3[[3]], type = "o"
     , xlab = "path size"
     , ylab = "RMSE"
     , main = paste("runs  = ", runs))



#____________-
Hurst_1 = 0.25
Hurst_2 = 0.4
Hurst_3 = 0.75
min_level = 10 #range of octaves to simulate over
max_level = 20 
runs = 1000


Bivaraite_1 <- delta_estimator_multivariate(c(Hurst_1,Hurst_1),min_level,max_level,runs)
Bivaraite_2 <- delta_estimator_multivariate(c(Hurst_2,Hurst_2),min_level,max_level,runs)
Bivaraite_3 <- delta_estimator_multivariate(c(Hurst_3 ,Hurst_3),min_level,max_level,runs)
Bivariate_mixed <- delta_estimator_multivariate(c(Hurst_1 ,Hurst_3),min_level,max_level,runs)

biases_1 <- Bivaraite_1[[1]]
biases_2 <- Bivaraite_2[[1]]
biases_3 <- Bivaraite_3[[1]]
biases_mixed <- Bivariate_mixed[[1]]

biases_1_as_dataframe<-as.data.frame(biases_1,col.names = c(min_level:max_level))
biases_2_as_dataframe<-as.data.frame(biases_2,col.names = c(min_level:max_level))
biases_3_as_dataframe<-as.data.frame(biases_3,col.names = c(min_level:max_level))
biases_mixed_as_dataframe<-as.data.frame(biases_mixed,col.names = c(min_level:max_level))

par(mfrow=c(2,2))

plot(c(min_level:max_level), biases_1_as_dataframe[1,] #- (2*0.4+1)
     ,ylim = c(0.5,2)
     ,xlab ="pathsize"
     ,ylab = "delta estimator"
     ,main = paste("Hurst: ", Hurst_1, "Runs = ", runs)
     ,type = "o") 
lines(c(min_level:max_level), biases_1_as_dataframe[2,]#- (2*0.4+1)
      ,type = "o")

plot(c(min_level:max_level), biases_2_as_dataframe[1,] #- (2*0.4+1)
     ,ylim = c(0.5,2)
     ,xlab ="pathsize"
     ,ylab = "delta estimator"
     ,main = paste("Hurst: ", Hurst_2, "Runs = ", runs)
     ,type = "o") 
lines(c(min_level:max_level), biases_2_as_dataframe[2,]#- (2*0.4+1)
      ,type = "o")

plot(c(min_level:max_level), biases_3_as_dataframe[1,] #- (2*0.4+1)
     ,ylim = c(2,3)
     ,xlab ="pathsize"
     ,ylab = "delta estimator"
     ,main = paste("Hurst: ", Hurst_3, "Runs = ", runs)
     ,type = "o") 
lines(c(min_level:max_level), biases_3_as_dataframe[2,]#- (2*0.4+1)
      ,type = "o")

plot(c(min_level:max_level), biases_mixed_as_dataframe[1,] #- (2*0.4+1)
     ,ylim = c(0.5,2)
     ,xlab ="pathsize"
     ,ylab = "delta estimator"
     ,main = paste("Hursts: ", Hurst_1, Hurst_3, "Runs = ", runs)
     ,type = "o") 
lines(c(min_level:max_level), biases_mixed_as_dataframe[2,]#- (2*0.4+1)
      ,type = "o")


TEST <- list(c(1:3),c(4:6))
T <- as.data.frame(TEST)

