# Oliver Orejola
# Created: 9/27/21
# 
#------------------------- [ Libraries ]----------------------------
library(somebm)
library(wavelets)
library(diptest)
library(MASS)
library("tidyverse")
#------------------------- [ Functions ]----------------------------
coordinate_matrix <- function(n){
  mat <- c()
  for(i in 1:n){
    x <- rnorm(n)
    col <- x/sqrt(sum(x^2)) 
    mat <- append(mat,col)
  }
  return(matrix(mat, n, n,byrow = FALSE))
}

low_dim_wavelet_sampe_covariances<- function(level,scales,Hursts, mixed = FALSE){
  N = 2^level #Path size
  #n_j = N/(2^scale)
  p = length(Hursts)
  P <- coordinate_matrix(p)
  wavelet_list <- list()
  #Create blank list of NA from which we will construct List of Vectors
  for(j in scales){wavelet_list <- append(wavelet_list, c(NA))}
  for(H in Hursts){
    fractional_brownian <-  N^H*fbm(hurst = H, n = N)
    wavelet_transform <- dwt(fractional_brownian, filter = "d4", n.levels = level, boundary = "reflection")
    i = 1
    for(j in scales){ 
      wavelet_coefficients <- unlist(wavelet_transform@W[j+1])
      wavelet_list[[i]] <- append(wavelet_list[[i]] ,wavelet_coefficients)
      i <- i+1
    }
    
  }
  # Remove NA generated by initiation of list of blank vectors
  for(i in 1:length(wavelet_list)){wavelet_list[[i]] <-wavelet_list[[i]][!is.na(wavelet_list[[i]])]}
  
  i=1
  for(j in scales){
    effective_sample_size = 2^(level-j)
    wavelet_mat <- matrix(wavelet_list[[i]], effective_sample_size, p,byrow = FALSE)  # convert vectors into matrices 
    if(mixed == TRUE){ 
      mixed_wavlet_mat <- wavelet_mat %*% t(P)
      mixed_wavlet_product <- crossprod(mixed_wavlet_mat)
      eigenvalues <- eigen(1/effective_sample_size *mixed_wavlet_product)$values #add list of eigenvalues
    }
    else{
      wavelet_product <-  crossprod(wavelet_mat)
      eigenvalues <- eigen(1/effective_sample_size *wavelet_product)$values
    }
    wavelet_list[[i]]  <- eigenvalues
    i=i+1
  }
  return(wavelet_list)
}

test<- low_dim_wavelet_sampe_covariances(8,c(4,5),c(0.2,0.8))
test
#------[ Simulations and Data generation ]----------
set.seed(1000)
#-----------------Regression -------------------------

delta_estimator <- function(hurst,min_level,max_level,runs){
  data <- c()
  data_sd <- c()
  data_RMSE <- c()
  j1 <- 3 #Fixed at 3 to match paper
  for(level in min_level:max_level){
    mc_delta<- c()
    data_SE <- c()
    j2 <- level - 2 # set j2 to  log_2(path_size) - number of vanishing moments
    l = j2-j1+1
    X <- matrix(c(c(j1:j2),rep(1,l)),2,l,byrow=TRUE)
    weights <- ginv(X)%*%c(1,0)
    for(r in 1:runs){
      wavelet_eigen <- low_dim_wavelet_sampe_covariances(level,c(j1:j2),hurst)
      delta <- 0
      for(i in 1:l){
        delta<- delta + weights[i]*log(wavelet_eigen[[i]],base=2)
      }
      data_SE <- append(data_SE, (delta - (2*hurst + 1))**2)
      mc_delta <-append(mc_delta,delta)
    }
    rescaled_delta <- (mc_delta - rep(1,length(mc_delta)))*0.5
    data <- append(data, mean(rescaled_delta))
    data_sd <- append(data_sd, sd(rescaled_delta ))
    data_RMSE <- append(data_RMSE,sqrt(mean(data_SE)))
  }
  return(list(data,data_sd,data_RMSE))
}


delta_estimator_multivariate <- function(hurst,min_level,max_level,runs){
  data <- list() #Initalize blank lists
  data_sd <- list()
  data_RMSE <- list()
  j1 <- 6 
  level_index=1
  for(level in min_level:max_level){
    mc_delta<- list()
    data_SE <- list()
    j2 <- level - 3 # set j2 to  log_2(path_size) - number of vanishing moments
    l = j2-j1+1
    X <- matrix(c(c(j1:j2),rep(1,l)),2,l,byrow=TRUE)
    weights <- ginv(X)%*%c(1,0)
    for(r in 1:runs){
      wavelet_eigen <- low_dim_wavelet_sampe_covariances(level,c(j1:j2),hurst)
      delta <- rep(0,length(hurst))
      for(i in 1:l){
        sorted_eigen_values <-sort(wavelet_eigen[[i]])
        delta<- delta + weights[i]*log(wavelet_eigen[[i]],base=2)
      }
      mc_delta[[r]] <- delta 
      data_SE[[r]] <- (delta - (2*hurst + 1))**2
      
    }
   mc_delta <- as.data.frame(mc_delta)
   data_SE <- as.data.frame(data_SE)
   data[[level_index]]<- apply(mc_delta,1,mean)
   data_sd[[level_index]]<- apply(mc_delta,1,sd)*0.5
   data_RMSE[[level_index]]<- sqrt(apply(data_SE,1,mean))
   level_index<- level_index+1
    #rescaled_delta <- (mc_delta - rep(1,length(mc_delta)))*0.5
    #data <- append(data, mean(rescaled_delta))
   # data_sd <- append(data_sd, sd(rescaled_delta ))
    #<- append(data_RMSE,sqrt(mean(data_SE)))
  }
  return(list(data,data_sd,data_RMSE))
}
test<- delta_estimator_multivariate(c(0.4,0.4),10,15,100)

Hurst_1 = 0.25
Hurst_2 = 0.4
Hurst_3 = 0.75
min_level = 10 #range of octaves to simulate over
max_level = 20 
runs = 1000


data_1 <- delta_estimator(Hurst_1,min_level,max_level,runs)
data_2 <- delta_estimator(Hurst_2,min_level,max_level,runs)
data_3 <- delta_estimator(Hurst_3,min_level,max_level,runs)

par(mfrow=c(3,3))

bias <- data_1[[1]] - Hurst_1
plot(c(min_level:max_level),bias, type = "l"
     , xlab = "path size"
     , ylab = "bias"
     , main = paste("Delta Estimator bias vs Path size, Hurst = ", Hurst_1))

plot(c(min_level:max_level),log(data_1[[2]],base=2), type = "o"
     , xlab = "path size"
     , ylab = "log_2(std)"
     , main = paste("runs  = ", runs))

plot(c(min_level:max_level),data_1[[3]], type = "o"
     , xlab = "path size"
     , ylab = "RMSE"
     , main = paste("runs  = ", runs))

bias <- data_2[[1]] - Hurst_2
plot(c(min_level:max_level),bias, type = "l"
     , xlab = "path size"
     , ylab = "bias"
     , main = paste("Delta Estimator bias vs Path size, Hurst = ", Hurst_2))

plot(c(min_level:max_level),log(data_2[[2]],base=2), type = "o"
     , xlab = "path size"
     , ylab = "log_2(std)"
     , main = paste("runs  = ", runs))

plot(c(min_level:max_level),data_2[[3]], type = "o"
     , xlab = "path size"
     , ylab = "RMSE"
     , main = paste("runs  = ", runs))


bias <- data_3[[1]] - rep(Hurst_3,length( data_3[[1]]))
plot(c(min_level:max_level),bias, type = "l"
     , xlab = "path size"
     , ylab = "bias"
     , main = paste("Delta Estimator bias vs Path size, Hurst = ", Hurst_3))

plot(c(min_level:max_level),log(data_3[[2]],base=2), type = "o"
     , xlab = "path size"
     , ylab = "log_2(std)"
     , main = paste("runs  = ", runs))

plot(c(min_level:max_level),data_3[[3]], type = "o"
     , xlab = "path size"
     , ylab = "RMSE"
     , main = paste("runs  = ", runs))



#____________-
Two_Hursts = c(0.25,0.75)
Three_Hursts = c(0.25,0.5,0.75)
Five_Hursts = c(0.1,0.3,0.5,0.7,0.9)
min_level = 10 #range of octaves to simulate over
max_level = 20 
runs = 1000


Bivaraite <- delta_estimator_multivariate(Two_Hursts, min_level,max_level,runs)
Multivaraite_3 <- delta_estimator_multivariate(Three_Hursts,min_level,max_level,runs)
Multivaraite_5 <- delta_estimator_multivariate(Five_Hursts ,min_level,max_level,runs)




Bivaraite_as_dataframe<-as.data.frame(Bivaraite[[1]],col.names = c(min_level:max_level))
Multivaraite_3_as_dataframe<-as.data.frame(Multivaraite_3[[1]],col.names = c(min_level:max_level))
Multivaraite_5_as_dataframe<-as.data.frame(Multivaraite_5[[1]],col.names = c(min_level:max_level))

par(mfrow=c(1,2))

plot(c(min_level:max_level), Bivaraite_as_dataframe[1,]*0.5 - 0.5
     ,ylim = c(0,1)
     ,xlab ="pathsize"
     ,ylab = "delta estimator"
     ,main = paste("Two Hurst: ", "Runs = ", runs)
     ,type = "o")
abline(h=0.75, col="blue")
abline(h=0.25, col="blue")
lines(c(min_level:max_level), Bivaraite_as_dataframe[2,] *0.5 - 0.5
      ,type = "o")

plot(c(min_level:max_level), Multivaraite_3_as_dataframe[1,] *0.5 - 0.5
     ,ylim = c(0,1)
     ,xlab ="pathsize"
     ,ylab = "delta estimator"
     ,main = paste("Three Hursts: ", "Runs = ", runs)
     ,type = "o") 
lines(c(min_level:max_level), Multivaraite_3_as_dataframe[2,]*0.5 - 0.5
      ,type = "o")
lines(c(min_level:max_level), Multivaraite_3_as_dataframe[3,]*0.5 - 0.5
      ,type = "o")
abline(h=0.25, col="blue")
abline(h=0.5, col="blue")
abline(h=0.75, col="blue")

plot(c(min_level:max_level), Multivaraite_5_as_dataframe[1,] *0.5 - 0.5
     ,ylim = c(0,1)
     ,xlab ="pathsize"
     ,ylab = "delta estimator"
     ,main = paste("Five Hurst: ", "Runs = ", runs)
     ,type = "o") 
lines(c(min_level:max_level), Multivaraite_5_as_dataframe[2,]*0.5 - 0.5
      ,type = "o")
lines(c(min_level:max_level), Multivaraite_5_as_dataframe[3,]*0.5 - 0.5
      ,type = "o")
lines(c(min_level:max_level), Multivaraite_5_as_dataframe[4,]*0.5 - 0.5,type = "o")
#lines(c(min_level:max_level), Multivaraite_5_as_dataframe[5,]*0.5 - 0.5,type = "o")

abline(h=0.1, col="blue" )
abline(h=0.3, col="blue")
abline(h=0.5, col="blue")
abline(h=0.7, col="blue")
abline(h=0.9, col="blue")
#----------
#----------
#----------
#----------
#----------
min_level = 10 #range of octaves to simulate over
max_level = 20 
Multivariate<- delta_estimator_multivariate(c(0.3,0.4,0.5,0.7,0.8,0.9), min_level,max_level,1000)
Multivariate_as_dataframe <-as.data.frame(Multivariate[[1]],col.names = c(min_level:max_level))

par(mfrow=c(1,1))
plot(c(min_level:max_level), Multivariate_as_dataframe [1,] *0.5 - 0.5
     ,ylim = c(0,1)
     ,xlab ="pathsize"
     ,ylab = "delta estimator"
     ,main = paste("Five Hurst: ", "Runs = ", runs)
     ,type = "o") 
lines(c(min_level:max_level),Multivariate_as_dataframe[2,]*0.5 - 0.5
      ,type = "o")
lines(c(min_level:max_level), Multivariate_as_dataframe[3,]*0.5 - 0.5
      ,type = "o")
lines(c(min_level:max_level), Multivariate_as_dataframe[4,]*0.5 - 0.5,type = "o")
lines(c(min_level:max_level), Multivariate_as_dataframe[5,]*0.5 - 0.5,type = "o")
lines(c(min_level:max_level), Multivariate_as_dataframe[6,]*0.5 - 0.5,type = "o")

abline(h=0.3, col="blue" )
abline(h=0.4, col="blue")
abline(h=0.5, col="blue")
abline(h=0.7, col="blue")
abline(h=0.8, col="blue")
abline(h=0.9, col="blue")
