# Oliver Orejola
# Created: 7/2/21
# Updated: 9/21/21
# 
#------------------------- [ Libraries ]----------------------------
library(somebm)
library(wavelets)
library(diptest)
library(MASS)

#------------------------- [ Functions ]----------------------------

coordinate_matrix <- function(n){
  mat <- c()
  for(i in 1:n){
    x <- rnorm(n)
    col <- x/sqrt(sum(x^2)) 
    mat <- append(mat,col)
  }
  return(matrix(mat, n, n,byrow = FALSE))
}

wavelet_sampe_covariance<- function(level,scale,p,Hursts, mixed = FALSE){
  N = 2^level
  n_j = N/(2^scale) #effective sample size
  wavelet_list <- c() 
  for(i in 1:p){
    H <- sample(Hursts,1)
    #MIXED<-  N^H*fbm(hurst = H, n = N) 
    fractional_brownian <-  N^H*fbm(hurst = H, n = N) ## OK! 
    wavelet_transform <- dwt(fractional_brownian, filter = "d4", n.levels = level, boundary = "reflection") #OK
    wavelet_list <- append(wavelet_list,unlist(wavelet_transform@W[scale]))
  }
  wavelet_mat<- matrix(wavelet_list, n_j, p,byrow = FALSE)
  
  if(mixed == TRUE){ 
    P <- coordinate_matrix(p)
    mixed_wavlet_mat <- wavelet_mat %*% t(P)
    mixed_wavlet_product <- crossprod(mixed_wavlet_mat)
    eigenvalues <- eigen(1/n_j*mixed_wavlet_product)$values
  }
  else{
    wavelet_product <-  crossprod(wavelet_mat)
    eigenvalues <- eigen(1/n_j*wavelet_product)$values
  }
  return(eigenvalues)
}

low_dim_wavelet_sampe_covariances<- function(level,scales,Hursts, mixed = FALSE){
  N = 2^level #Path size
  #n_j = N/(2^scale)
  p = length(Hursts)
  P <- coordinate_matrix(p)
  wavelet_list <- list()
  for(j in scales){
    wavelet_list <- append(wavelet_list, c(NA))
  }
  for(H in Hursts){
    fractional_brownian <-  N^H*fbm(hurst = H, n = N) 
    wavelet_transform <- dwt(fractional_brownian, filter = "d2", n.levels = level, boundary = "reflection")
    i = 1
    for(j in scales){  
      wavelet_list[[i]] <- append(wavelet_list[[i]] ,unlist(wavelet_transform@W[j]))
      i <- i+1
    }
  }
  # Remove NA generated by initiation of list of blank vectors
  for(i in 1:length(wavelet_list)){
    wavelet_list[[i]] <-wavelet_list[[i]][!is.na(wavelet_list[[i]])]
  }

  i=1
  for(j in scales){
    effective_sample_size = N/(2^j) #
    wavelet_mat <- matrix(wavelet_list[[i]], effective_sample_size, p,byrow = FALSE)  # convert vectors into matrices 
    if(mixed == TRUE){ 
      mixed_wavlet_mat <- wavelet_mat %*% t(P)
      mixed_wavlet_product <- crossprod(mixed_wavlet_mat)
      eigenvalues <- eigen(1/effective_sample_size *mixed_wavlet_product)$values #add list of eigenvalues
    }
    else{
      wavelet_product <-  crossprod(wavelet_mat)
      eigenvalues <- eigen(1/effective_sample_size *wavelet_product)$values
    }
    wavelet_list[[i]]  <- eigenvalues
    i=i+1
  }
  return(wavelet_list)
}


test <- low_dim_wavelet_sampe_covariances(10,c(4,5,6),c(0.5,0.5,0.5,0.5))
test[[1]]
test[[2]]
length(test[[2]])
#---------------------- Low dimensional problem

#--- 
vector_of_hursts_4 <- c(0.2,0.4,0.6,0.8)
vector_of_hursts_2  <- c(0.25,0.25,0.75,0.75)
vector_of_hursts_1 <- c(0.5,0.5,0.5,0.5)
single_hurst <- 0.5
SCALES <- c(6:17)
ev_1 <- c()
ev_2 <- c()
ev_3 <- c()
ev_4 <- c()

ev_1_sum <- rep(0,length(SCALES))
ev_2_sum <- rep(0,length(SCALES))
ev_3_sum <- rep(0,length(SCALES))
ev_4_sum <- rep(0,length(SCALES))

runs = 1000
for(r in 1:runs){
  ev_1 <- c()
# ev_2 <- c()
 # ev_3 <- c()
 # ev_4 <- c()
  data <- low_dim_wavelet_sampe_covariances(18,SCALES,single_hurst)
  i=1
  for(scale in SCALES){
    level = 19
    E <-(log(data[[i]],base=2)/scale-1)*(1/2) 
    E <- sort(E)
    print(E)
    ev_1 <- append(ev_1,E[1])
    #ev_2 <- append(ev_2,E[2])
    #ev_3 <- append(ev_3,E[3])
    #ev_4 <- append(ev_4,E[4])
    i = i+1
  }
  ev_1_sum <- ev_1_sum + ev_1
 # ev_2_sum <- ev_2_sum + ev_2
 # ev_3_sum <- ev_3_sum + ev_3
 # ev_4_sum <- ev_4_sum + ev_4
}

avg_ev_1 <- ev_1_sum/runs
# avg_ev_2 <- ev_2_sum/runs
# avg_ev_3 <- ev_3_sum/runs
# avg_ev_4 <- ev_4_sum/runs

plot(SCALES,avg_ev_1
     ,col ="red",type = "l"
     ,ylim = c(0,0.5),ylab = "eigenvalues"
     ,main = "Single Hurst, H = 0.5")
#lines(SCALES,avg_ev_2,col="blue")
#lines(SCALES,avg_ev_3,col="green")
#lines(SCALES,avg_ev_4,col="purple")

Linear_Model<-lm(avg_ev_1~SCALES)
summary(Linear_Model)

#_____________________ High dimensional Limit_______________________
ev_1 <- c()
ev_2 <- c()
ev_3 <- c()
ev_4 <- c()
levels  <- c(8:16)
ev_1_sum <- rep(0,length(levels))
ev_2_sum <- rep(0,length(levels))
ev_3_sum <- rep(0,length(levels))
ev_4_sum <- rep(0,length(levels))
runs = 25
vector_of_hursts_1 <- c(0.5,0.5,0.5,0.5) # dimension fixed = 4
for(r in runs){
  ev_1 <- c()
  ev_2 <- c()
  ev_3 <- c()
  ev_4 <- c()
  for(level in levels){
    scale <- level - 3
    E <- log(low_dim_wavelet_sampe_covariances(level,scale,vector_of_hursts_1)[[1]],base=2)/scale
    E <- sort(E)
    ev_1 <- append(ev_1,E[1])
    ev_2 <- append(ev_2,E[2])
    ev_3 <- append(ev_3,E[3])
    ev_4 <- append(ev_4,E[4])
  }
  ev_1_sum <- ev_1_sum + ev_1
  ev_2_sum <- ev_2_sum + ev_2
  ev_3_sum <- ev_3_sum + ev_3
  ev_4_sum <- ev_4_sum + ev_4
}
  
avg_ev_1 <- ev_1_sum/runs
avg_ev_2 <- ev_2_sum/runs
avg_ev_3 <- ev_3_sum/runs
avg_ev_4 <- ev_4_sum/runs


plot(levels,avg_ev_1
     ,col ="red",type = "l"
     ,ylim = c(0,1),ylab = "eigenvalues"
     ,main = "Single Hurst, H = 0.5")
lines(levels,avg_ev_2,col="blue")
lines(levels,avg_ev_3,col="green")
lines(levels,avg_ev_4,col="purple")

#____________________________________________
Hurst = 0.50
level = 18
#scale = 4
pathsize <- 2^level
FBM <- (pathsize)^Hurst*fbm(Hurst,n=pathsize)
plot(FBM)

d_wavelet_transform <- dwt(FBM,filter="d4", n.levels = level, boundary = "reflection")
wavelet_transform_4 <- unlist(d_wavelet_transform@W[4])
wavelet_transform_5 <- unlist(d_wavelet_transform@W[5])
wavelet_transform_6 <- unlist(d_wavelet_transform@W[6])
wavelet_transform_7 <- unlist(d_wavelet_transform@W[7])
v_4 <- var(wavelet_transform_4)
v_5 <- var(wavelet_transform_5)
v_6 <- var(wavelet_transform_6)
v_7 <- var(wavelet_transform_7)

log_variances <- log(c(v_4,v_5,v_6,v_7),base=2)
c(4:7)
Linear_Model<-lm(log_variances~c(4:7))
summary(Linear_Model)

#----- MSD ------
level = 12
#scale = 4
pathsize <- 2^level
hurst_1 <- 0.25
hurst_2 <- 0.75
scales <- c(4:11)
data_1 <- rep(0,length(scales))
data_2 <- rep(0,length(scales))
runs = 50
for(r in 1:runs){
FBM_1 <- (pathsize)^hurst_1*fbm(hurst_1 ,n=pathsize)
FBM_2 <- (pathsize)^hurst_2*fbm(hurst_2,n=pathsize)
log_MSD_1 <- c()
log_MSD_2 <- c()
for(j in scales){
  MSD_scale_1 <- (log(mean(diff(FBM_1,2^j)^2),base=2)/j)*1/2
  MSD_scale_2 <- (log(mean(diff(FBM_2,2^j)^2),base=2)/j)*1/2
  log_MSD_1 <- append(log_MSD_1,MSD_scale_1)
  log_MSD_2 <- append(log_MSD_2,MSD_scale_2)
}
data_1 <- data_1 + log_MSD_1 
data_2 <- data_2 + log_MSD_2
}

H_1 <- rep(hurst_1,length(data_1))
H_2 <- rep(hurst_2,length(data_2))
data_1 <- data_1/runs - H_1
data_2 <- data_2/runs - H_2

par(mfrow = c(2,1))
plot(scales,data_1,type = "o", main = "H = 0.25")
plot(scales,data_2,type = "o", main = "H = 0.75")

#---------- MEAN SQUARED DIFFERENCE 
levels = 11
pathsize = 2^levels
hurst = 0.25
scales <- c(4:6)
FBM <- pathsize^hurst*fbm(hurst, pathsize)

MSD_data <- c()
for(j in scales){
  MSD <- mean(diff(FBM,2^j)^2)
  MSD_data <- append(MSD_data,MSD)
}
Linear_Model<-lm(log(M,base=2)~c(4,5,6))
summary(Linear_Model)$coefficients[2,1]


#-----------------Regression -------------------------
j1 <- 5
j2 <- 8
l = j2-j1+1
c(c(j1:j2),rep(1,l))
X <- matrix(c(c(j1:j2),rep(1,l)),2,l,byrow=TRUE)
X
null_space <- Null(t(X))
weights <- ginv(X)%*%c(1,0)
weights 

Hurst = 0.25
level = 16

delta <- 0
data <- c()
runs = 100

for(level in 11:level){
  avg_delta <- 0
  for(r in 1:runs){
    wavelet_eigen <- low_dim_wavelet_sampe_covariances(level,c(j1:j2),Hurst)
    delta <- 0
    for(i in 1:l){
      delta<- delta + weights[i]*log(wavelet_eigen[[i]],base=2)
    }
    avg_delta <-avg_delta+delta
  }
  data <- append(data,avg_delta)
}
data <- data/runs

data_rescale <- (data - 1)*0.5
#data75<-data
#data05 <-data
data25 <-data_rescale 
par(mfrow=c(1,1))

plot(c(11:level),data25, type = "l"
     , xlab = "path size"
     , ylab = "delta"
     , main = "Def 3.2 vs path size. Hurst = 0.25, j1 = 5 j2 = 8")
plot(c(11:level),data05, type = "l"
     , xlab = "path size"
     , ylab = "delta"
     , main = "Def 3.2 vs path size. Hurst = 0.50, j1 = 6 j2 = 11")
plot(c(11:level),data75, type = "l"
     , xlab = "path size"
     , ylab = "delta"
     , main = "Def 3.2 vs path size. Hurst = 0.75, j1 = 6 j2 = 11")




