---
title: "Test Analysis"
author: "Oliver Orejola"
date: "10/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Relevant Libraries


```{r libraries}
library(somebm)
library(wavelets)
library(MASS)
library(diptest)
library(ggplot2)
library(data.table)
library(dplyr)
library(latex2exp)
```

## Functions


```{r Functions}

coordinate_matrix <- function(n){
  mat <- c()
  for(i in 1:n){
    x <- rnorm(n)
    col <- x/sqrt(sum(x^2)) 
    mat <- append(mat,col)
  }
  return(matrix(mat, n, n,byrow = FALSE))
}

probabilistic_wavelet_sample_covariances<- function(level,scales,dimension,Hursts, mixed = FALSE){
  N = 2^level #Path size
  #n_j = N/(2^scale)
  P <- coordinate_matrix(dimension)
  wavelet_list <- list()
  #Create blank list of NA from which we will construct List of Vectors
  for(j in scales){wavelet_list <- append(wavelet_list, c(NA))}
  for(p in 1:dimension){
    H <- sample(Hursts,1)
    fractional_brownian <-  N^H*fbm(hurst = H, n = N)
    wavelet_transform <- dwt(fractional_brownian, filter = "d4", n.levels = level, boundary = "reflection")
    i = 1
    for(j in scales){ 
      wavelet_coefficients <- unlist(wavelet_transform@W[j+1])
      wavelet_list[[i]] <- append(wavelet_list[[i]] ,wavelet_coefficients)
      i <- i+1
    }
  }
  # Remove NA generated by initiation of list of blank vectors
  for(i in 1:length(wavelet_list)){wavelet_list[[i]] <-wavelet_list[[i]][!is.na(wavelet_list[[i]])]}
  
  i=1
  for(j in scales){
    effective_sample_size = 2^(level-j)
    wavelet_mat <- matrix(wavelet_list[[i]], effective_sample_size, p,byrow = FALSE)  # convert vectors into matrices 
    if(mixed == TRUE){ 
      mixed_wavlet_mat <- wavelet_mat %*% t(P)
      mixed_wavlet_product <- crossprod(mixed_wavlet_mat)
      eigenvalues <- eigen(1/effective_sample_size *mixed_wavlet_product)$values #add list of eigenvalues
    }
    else{
      wavelet_product <-  crossprod(wavelet_mat)
      eigenvalues <- eigen(1/effective_sample_size *wavelet_product)$values
    }
    wavelet_list[[i]]  <- eigenvalues
    i=i+1
  }
  return(as.data.frame(wavelet_list,col.names =  scales))
}

wavelet_regression_estimator <- function(level,j1, window_size, dimension,Hursts, mixed = FALSE){
  
  scale_max <- level-log(dimension,base=2)
  log_wavelet_eigevalues <- log(probabilistic_wavelet_sample_covariances(level,c(j1:scale_max),dimension,Hursts, mixed),base=2)
  estimate<-c()
  index<-1
  init_j2 <- j1 + window_size-1
  
  for( j2 in c(init_j2:scale_max)){
    L = length(c(j1:j2))
    X <- matrix(c(c(j1:j2),rep(1,L)),2,L,byrow=TRUE)
    weights <- ginv(X)%*%c(1,0)
    delta <- rep(0,dimension)
   # print(j2)
    l <-1
    for(j in c(j1:j2)){
    delta <- delta + weights[l]*log_wavelet_eigevalues[l]
    l <- l + 1
    }
    estimate[index]<- delta
    index <- index + 1
  }
  return(estimate)
}

monte_carlo_probability_of_rejection <- function(runs,dip_test_significance,level,j1, window_size, dimension,Hursts, mixed = FALSE){
  scale_max <- level-log(dimension,base=2)
  init_j2 <- j1 + window_size-1
  number_of_estimates <- length(c(init_j2:scale_max))
  counts <-  rep(0,number_of_estimates)
  for(i in 1:runs){
    if(i %% 100 ==0){
      print(paste("run :", i))
      print(counts)
    }
    estimate <- wavelet_regression_estimator(level,j1,window_size,dimension,Hursts, mixed)
    for( j in c(1: number_of_estimates)){
    
      pvalue<-dip.test(unlist(estimate[j]))$p.value
      if( pvalue<= dip_test_significance){
      counts[j]  <- counts[j] + 1
      #print("reject")
     }
    }
  }
  proportion_of_rejections <- counts/runs
  return(proportion_of_rejections)
}

```

## Size Analysis
Test Size of test. 


```{r}
runs = 1000
level = 14
pathsize = 2^12
dimension = 2^6
j1 = 2
init_window = 3
Hursts = 0.5
sig_levels <-  c(seq(0.05,0.95,by = 0.05),seq(0.955,1,by = 0.015))
alphas <-list()
index <- 1

for(sig in sig_levels){
  test <- monte_carlo_probability_of_rejection(runs,sig,level,j1,init_window,dimension,Hursts)
  print(paste("dip_test_significance:" ,sig))
  print(test)
  alphas[[index]]<- test
  index <- index + 1 
}
alphas <- as.data.frame(alphas,col.names = sig_levels)
#write.csv(alphas,"size_of_test_pathsize_14_H05_j1_2_initwindow_3")
```

```{r}
sig_levels <-  c(seq(0.05,0.95,by = 0.05),seq(0.955,1,by = 0.015))
alphas <- subset(read.csv("size_of_test_pathsize_14_H05_j1_2_initwindow_3"),select = c(1:length(sig_levels )+1))
alphas
```

```{r}
t_alphas <- transpose(alphas)
t_alphas["sig"] <- sig_levels
names(t_alphas) <- c(4:8,"sig")
new_alphas<- t_alphas %>%
  pivot_longer(cols=c(1:5),names_to = "J2",values_to = "alpha")

new_alphas
```

```{r}
ggplot(data=new_alphas)+
  geom_line(aes(x=sig,y=alpha,colour=J2))+
  xlab("Dip Test Significance Level")+
  ylab("Proportion of rejection")+
  labs( title = TeX("$H$ = 0.5, N = $2^{14}, p = $2^6$, $j_1$ = 2"))
  

```



## Power Analysis

Test Power of test. H1= 0.1 to H2=0.3
```{r Parameters}
runs = 1000
level = 14
Pathsize = 2^level
j1 = 2
init_window = 3
dimension = 2^6

proportion_of_rejections <- list()
H2 <- seq(0.13, 0.3, by=0.01)
H1 <- rep(0.1, length(H2))
Hursts <- Map(c,H1,H2)
dip_test_significance <- 0.35
index <- 1
for(H in Hursts){
  print(H)
  test <- monte_carlo_probability_of_rejection(runs,dip_test_significance,level,j1,init_window,dimension,H)
  proportion_of_rejections[[index]] <- test
  index <- index + 1
}
proportion_of_rejections <- as.data.frame(proportion_of_rejections, colnames(H2))
names(proportion_of_rejections) = H2
#write.csv(proportion_of_rejections,"proportion_of_rejections_pathsize_14_H1=01_j1_2_initwindow_3")
```


```{r}
H2<- seq(0.13, 0.3, by=0.01)
proportion_of_rejections<- subset(read.csv("proportion_of_rejections_pathsize_14_H1=01_j1_2_initwindow_3"),select = c(1:length(H2)+1))
proportion_of_rejections
t_proportion_of_rejections <- transpose(proportion_of_rejections)
t_proportion_of_rejections["H2"] <- H2
t_proportion_of_rejections
ggplot(t_proportion_of_rejections)+
  geom_line(mapping=aes(x=H2,y=V1))+
  xlab(TeX("$H_2$"))+
  ylab("Proportion of rejections")+
  labs( title = TeX("$H_1$ = 0.1, N = $2^{14}, p = $2^6$, $j_1$ = 2, $j_2$ = 4" ))
```

Test Power of test. H1= 0.6 to H2=0.9
```{r Parameters}
runs = 1000
level = 14
Pathsize = 2^level
j1 = 2
init_window = 3
dimension = 2^6

proportion_of_rejections_2 <- list()
H2 <- seq(0.63, 0.9, by=0.01)
H1 <- rep(0.6, length(H2))
Hursts <- Map(c,H1,H2)
dip_test_significance <- 0.35
index <- 1
for(H in Hursts){
  print(H)
  test <- monte_carlo_probability_of_rejection(runs,dip_test_significance,level,j1,init_window,dimension,H)
  proportion_of_rejections[[index]] <- test
  index <- index + 1
}
proportion_of_rejections_2 <- as.data.frame(proportion_of_rejections, colnames(H2))

names(proportion_of_rejections_2) = H2
#write.csv(proportion_of_rejections_2,"proportion_of_rejections_pathsize_14_H1=06_j1_2_initwindow_3")
```

```{r}
H2 <- seq(0.63, 0.9, by=0.01)
proportion_of_rejections<- subset(read.csv("proportion_of_rejections_pathsize_14_H1=06_j1_2_initwindow_3"),select = c(1:length(H2)+1))
proportion_of_rejections
t_proportion_of_rejections <- transpose(proportion_of_rejections)
t_proportion_of_rejections["H2"] <- H2
t_proportion_of_rejections
ggplot(t_proportion_of_rejections)+
  geom_line(mapping=aes(x=H2,y=V1))+
  xlab(TeX("$H_2$"))+
  ylab("Proportion of rejections")+
  labs( title = TeX("$H_1$ = 0.6, N = $2^{14}, p = $2^6$, $j_1$ = 2, $j_2$ = 4" ))
```
# Plots

## Histograms

```{r}
level = 14
diff <- 0.2
H1 <- seq(0.1,0.6, by =0.1)
H2 <- seq(0.1,0.6, by =0.1) +diff
Hursts <- Map(c,H1,H2)

par(mfrow=c(2,3))
for(H in Hursts){
  #Mixed H1 H2
  hist(log2(probabilistic_wavelet_sample_covariances(level,c(2:6),2^6,H)$X5)*0.5/5-0.5, breaks = 32,
     xlab = "log(eigenvalues)*0.5/5-0.5",
     xlim = c(-1,1),
     main = paste("H1 =", H[1], "H2 =", H[2]))#,"pathsize =2^",level, "dimension =2^", 6))
  abline(v=H[1], col="blue" )
  abline(v=H[2], col="blue" )
  
}



#qqplot(logeigendistH2,logeigendistH1)
```


```{r}
H2 <- seq(0.13, 0.3, by=0.01)
H1 <- rep(0.1, length(H2))
plot(H2-H1,proportion_of_rejections[1,] 
     ,type = "o"
     ,xlab = "Hurst2 - Hurst1"
     ,ylab= "Proportion of rejections"
     ,main = "dip sig=0.4, dimension = 2^6 j1 = 2, j2 = 4, H1 = 0.1")

```

```{r}
monte_carlo_probability_of_rejection(runs,0.4,level,j1,init_window,dimension,c(0.6,0.99))
```
```{r}
runs = 1000
level = 12
Pathsize = 2^12
j1 = 2
init_window = 3
dimension = 2^6

proportion_of_rejections2 <- list()
H2 <- seq(0.12, 0.4, by=0.01)
H1 <- rep(0.1, length(H2))
Hursts <- Map(c,H1,H2)
dip_test_significance <- 0.9
index <- 1
for(H in Hursts){
  print(H)
  test <- monte_carlo_probability_of_rejection(runs,dip_test_significance,level,j1,init_window,dimension,H)
  proportion_of_rejections2[[index]] <- test
  index <- index + 1
}
proportion_of_rejections2 <- as.data.frame(proportion_of_rejections2, colnames(H2))

```

```{r}
H2 <- seq(0.12, 0.4, by=0.01)
H1 <- rep(0.1, length(H2))
plot(H2-H1,proportion_of_rejections2[2,] 
     ,type = "o"
     ,xlab = "Hurst2 - Hurst1"
     ,ylab= "Proportion of rejections"
     ,main = "dip sig=0.9, dimension = 2^6 j1 = 2, j2 = 5, H1 = 0.1")

```

```{r}
runs = 1000
level = 12
Pathsize = 2^12
j1 = 2
init_window = 3
dimension = 2^6

proportion_of_rejections3 <- list()
H2 <- seq(0.6, 0.95, by=0.01)
H1 <- rep(0.6, length(H2))
Hursts <- Map(c,H1,H2)
dip_test_significance <- 0.4
index <- 1
for(H in Hursts){
  print(H)
  test <- monte_carlo_probability_of_rejection(runs,dip_test_significance,level,j1,init_window,dimension,H)
  proportion_of_rejections3[[index]] <- test
  index <- index + 1
}
proportion_of_rejections3 <- as.data.frame(proportion_of_rejections3, col.names=paste("H2",H2))

```

```{r}
H2 <- seq(0.6, 0.95, by=0.01)
H1 <- rep(0.6, length(H2))
plot(H2-H1,proportion_of_rejections3[1,] 
     ,type = "o"
     ,xlab = "Hurst2 - Hurst1"
     ,ylab= "Proportion of rejections",ylim = c(0,1)
     ,main = "dip sig=0.4, dimension = 2^6 j1 = 2, j2 = 4, H1 = 0.6")

```

```{r}
runs = 1000
level = 12
Pathsize = 2^12
j1 = 2
init_window = 3
dimension = 2^6

proportion_of_rejections_more <- list()
H2 <- seq(0.95, 0.999, by=0.005)
H1 <- rep(0.6, length(H2))
Hursts <- Map(c,H1,H2)
dip_test_significance <- 0.4
index <- 1
for(H in Hursts){
  print(H)
  test <- monte_carlo_probability_of_rejection(runs,dip_test_significance,level,j1,init_window,dimension,H)
  proportion_of_rejections_more[[index]] <- test
  index <- index + 1
}
proportion_of_rejections_more <- as.data.frame(proportion_of_rejections_more, colnames(H2))


```
```{r}
H2 <- c(seq(0.6, 0.95, by=0.01),seq(0.95, 0.999, by=0.005))
H1 <- rep(0.6, length(H2))
plot(H2-H1,c(unlist(proportion_of_rejections3[1,]),unlist(proportion_of_rejections_more[1,]))
     ,type = "o"
     ,xlab = "Hurst2 - Hurst1"
     ,ylab= "Proportion of rejections",ylim = c(0,1)
     ,main = "dip sig=0.4, dimension = 2^6 j1 = 2, j2 = 4, H1 = 0.6")

```